apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  annotations:
  "helm.sh/hook": post-install
  #"helm.sh/hook-weight": "1"
  #"helm.sh/hook-delete-policy": before-hook-creation
spec:
  addresses:
  - {{ .Values.ipaddresspool.ip_range | quote }}
  avoidBuggyIPs: true
