apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb
  annotations:
    "helm.sh/hook": post-install
spec:
  nodeSelectors:
    - matchLabels:
        node-role.kubernetes.io/worker: ""

