apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  nodeSelectors:
    - matchLabels:
        node-role.kubernetes.io/worker: ""

