apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/hook: PostSync
    #"helm.sh/hook-weight": "1"
    #"helm.sh/hook-delete-policy": before-hook-creation
spec: {}
