apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: metallb-system
  annotations:
    "helm.sh/hook": post-install
    #"helm.sh/hook-weight": "1"
    #"helm.sh/hook-delete-policy": before-hook-creation
spec: {}
